# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('is_removed', models.BooleanField(default=False)),
                ('customer_id', models.UUIDField(default=uuid.UUID('774cde56-4894-473c-932e-6271754d3908'), editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('phone_nr', models.IntegerField()),
                ('email', models.EmailField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('status', model_utils.fields.StatusField(choices=[('new', 'new'), ('promotions', 'promotions'), ('sales', 'sales')], default='new', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('product_id', models.UUIDField(default=uuid.UUID('bdc6c6e6-9c26-4d65-bbf8-d6c5af05d12a'), editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
