# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171206_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
