# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171205_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='no description', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='NoName', max_length=50),
        ),
    ]
