# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171207_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopbucket',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
    ]
