# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171205_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('status', model_utils.fields.StatusField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('shop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
