# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('rtv', 'rtv'), ('media', 'media')], default='rtv', max_length=50),
        ),
    ]
