# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shopbucket_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
    ]
