# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('status', model_utils.fields.StatusField(choices=[('new', 'new'), ('to_pay', 'to_pay'), ('payed', 'payed'), ('error', 'error'), ('returned', 'returned')], default='new', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 12, 5, 18, 57, 6, 49857, tzinfo=utc))),
                ('paid', models.DateTimeField()),
                ('sum', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='shop_num',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Shop'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Shop'),
        ),
    ]
