# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171207_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='product_uuid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_orderproducts', to='api.Product'),
        ),
    ]
