# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171205_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'cash'), ('payu', 'payu'), ('card', 'CARD')], default='cash', max_length=20),
        ),
    ]
