# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171207_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shop_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_order', to='api.Shop'),
        ),
    ]
