# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171207_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_uuid',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shop_uuid',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='orderproducts',
            old_name='order_uuid',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderproducts',
            old_name='product_uuid',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='shopbucket',
            old_name='customer_uuid',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shopbucket',
            old_name='product_uuid',
            new_name='product',
        ),
    ]
