# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171205_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
