# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171207_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_changed',
        ),
        migrations.AddField(
            model_name='order',
            name='STATUS',
            field=models.CharField(choices=[('new', 'new'), ('to_pay', 'to_pay'), ('paid', 'paid'), ('error', 'error'), ('returned', 'returned')], default='new', max_length=20),
        ),
    ]
