# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171208_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='STATUS',
            new_name='status',
        ),
    ]
