# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='shop_num',
        ),
        migrations.AddField(
            model_name='stock',
            name='in_reservation',
            field=models.SmallIntegerField(default=0),
        ),
    ]
