# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171212_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
