# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171215_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payuID',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
